name: soccernet-calibration
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pytorch==1.10.0
  - torchvision==0.11.1
  - numpy
  - pillow
  - tqdm
  - opencv
  - matplotlib
  - pyyaml
  - gdown
  - zipfile
  - pip==23.3.1
  - pip:
    - SoccerNet==0.1.23
