name: soccernet-calibration
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python==3.9
  - pytorch==1.10.0
  - torchvision==0.11.1
  - numpy
  - pillow
  - tqdm
  - opencv
  - matplotlib
  - pyyaml
  - gdown
  - pip
  - pip:
    - SoccerNet==0.1.23
